In [2]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories
cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 160005, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 160005 205000]
 [530000 310000 205000 170000 115000 145000]]


Part 2: Basic Array Understanding
Question 1: Array Dimensions
The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

Number of dimensions in sales_data
Shape of sales_data
Total number of values
Data type of the array
Memory occupied by the array

In [ ]:
print("no.of dimensions: ",sales_data.ndim)
print("shape: ",sales_data.shape)
print("total values: ",sales_data.size)
print("Data type:",sales_data.dtype)
print("Memory occupied: ",sales_data.nbytes)

no.of dimensions:  2
shape:  (5, 6)
total values:  30
Data type: int64
Memory occupied:  240


Question 2: Store and Category Count
Calculate the following:

Total number of stores
Total number of product categories
Total number of store-category combinations

In [ ]:
print("Total number of stores: ",stores.size)
print("Total number of products: ",categories.size)
print("Total number of store-category combinations: ",sales_data.size)

Total number of stores:  5
Total number of products:  6
Total number of store-category combinations:  30


Question 3: Sales Data Type Conversion
The reporting application requires sales values in floating-point format.

Convert sales_data into:

float32
float64
Compare the memory used by both arrays.

In [ ]:
sales_float32=sales_data.astype(np.float32)
sales_float64=sales_data.astype(np.float64)
print("sales_data into float32: ",sales_float32.dtype)
print("sales_data into float32: ",sales_float64.dtype)
print("memory of sales_data32: ",sales_float32.nbytes,"bytes")
print("memory of sales_data64: ",sales_float64.nbytes,"bytes")

sales_data into float32:  float32
sales_data into float32:  float64
memory of sales_data32:  120 bytes
memory of sales_data64:  240 bytes


Part 3: Indexing and Data Extraction
Question 4: Bengaluru Store Analysis
The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

In [ ]:
print("Bengaluru sales for all product categories: ",sales_data[0])

Bengaluru sales for all product categories:  [850000 420000 310000 275000 190000 225000]


Question 5: Mumbai Cost Analysis
Extract the total cost incurred by the Mumbai store for all product categories.

In [ ]:
print("total cost incurred by the Mumbai store: ",sum(cost_data[3]))

total cost incurred by the Mumbai store:  2060005


Question 6: Electronics Sales Across Stores
The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from sales_data.

In [ ]:
print("electronic sales in all stores: ",sales_data[:,0])

electronic sales in all stores:  [ 850000  780000  920000 1050000  690000]


Question 7: Clothing Cost Across Stores
Extract the Clothing cost for every store from cost_data.

In [ ]:
print("Clothing cost for every store from cost data: ",cost_data[:,2])

Clothing cost for every store from cost data:  [220000 210000 245000 265000 205000]


Question 8: Hyderabad Furniture Performance
Find the following for Hyderabad:

Furniture sales
Furniture cost
Furniture profit

In [ ]:
sales=sales_data[1,3]
cost=cost_data[1,3]
print("Furniture sales: ",sales)
print("Furniture cost: ",cost)
profit=sales-cost
print("profits: ",profit)


Furniture sales:  310000
Furniture cost:  225000
profits:  85000


Question 9: Chennai Category Range
Extract Chennai’s sales for the following categories:

Groceries
Clothing
Furniture
Use array slicing.

In [ ]:
print("chennai sales: ",sales_data[2,1:4])

chennai sales:  [390000 340000 260000]


Question 10: Selected Store Analysis
Extract sales data for:

Bengaluru
Chennai
Pune
Include only:

Electronics
Clothing
Beauty
Use advanced indexing.

In [ ]:
print("sale store analysis: ",sales_data[[0,2,4]][:,[0,2,4]])

sale store analysis:  [[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


Part 4: Sales Aggregation
Question 11: Company-Wide Sales
Calculate the total sales revenue generated by all stores and all categories.

In [ ]:
print("total sales: ", sales_data.sum())

total sales:  11675000


Question 12: Store-Wise Sales
Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format:

Bengaluru: total sales
Hyderabad: total sales
Chennai: total sales
Mumbai: total sales
Pune: total sales

In [ ]:
total_sales = np.sum(sales_data, axis=1)
for store, sales in zip(stores, total_sales):
    print(f"{store}: {sales}")

Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000


Question 13: Category-Wise Sales
Calculate total sales for each product category across all stores.

Display each category name with its total sales.

In [ ]:
category_sales = np.sum(sales_data, axis=0)
for category, sales in zip(categories, category_sales):
    print(f"{category}: {sales}")

Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Beauty: 1010000
Sports: 1175000


Question 14: Average Sales Per Store
Calculate the average sales generated by each store across all six product categories.

In [ ]:
avg_sales = np.mean(sales_data, axis=1)
for store, avg in zip(stores, avg_sales):
    print(f"{store}: {avg}")

Bengaluru: 378333.3333333333
Hyderabad: 382500.0
Chennai: 385000.0
Mumbai: 470000.0
Pune: 330000.0


Question 15: Average Sales Per Category
Calculate the average sales of each product category across the five stores.

In [ ]:
avg_sales=np.mean(sales_data,axis=0)
for category,avg in zip(categories,avg_sales):
  print(f"{category}:{avg}")

Electronics:858000.0
Groceries:437000.0
Clothing:320000.0
Furniture:283000.0
Beauty:202000.0
Sports:235000.0


Question 16: Highest-Selling Store
Identify:

Index of the store with the highest total sales
Name of the store
Total sales generated by that store
Use np.argmax().

In [ ]:
total_sales=np.sum(sales_data,axis=1)
max_index=np.argmax(total_sales)
print("Index of the store with the highest total: ",max_index)
print("Name of the store:", stores[max_index])
print("Total sales generated by that store: ",total_sales[max_index])

Index of the store with the highest total:  3
Name of the store: Mumbai
Total sales generated by that store:  2820000


Question 17: Lowest-Selling Store
Identify the store with the lowest overall sales.

Use np.argmin().

In [ ]:
total_sales=np.sum(sales_data,axis=1)
min_index=np.argmin(total_sales)
print("name of store with lowest sales:",stores[min_index])

name of store with lowest sales: Pune


Question 18: Highest-Selling Category
Find the product category that generated the highest total sales across the company.

In [ ]:
total_sales=np.sum(sales_data,axis=0)
max_index=np.argmax(total_sales)
print("Index of the category with the highest total: ",max_index)
print("Name of the category:", categories[max_index])
print("Total sales generated by that category: ",total_sales[max_index])

Index of the category with the highest total:  0
Name of the category: Electronics
Total sales generated by that category:  4290000


Question 19: Lowest-Selling Category
Find the product category with the lowest total sales across all stores.

In [ ]:
total_sales=np.sum(sales_data,axis=0)
mix_index=np.argmin(total_sales)
print("Index of the category with the lowest total: ",mix_index)
print("Name of the category:", categories[mix_index])
print("Total sales generated by that category: ",total_sales[min_index])

Index of the category with the lowest total:  4
Name of the category: Beauty
Total sales generated by that category:  1010000


Part 5: Cost Analysis
Question 20: Total Company Cost
Calculate the total cost incurred by SmartMart across all stores and product categories.

In [ ]:
total_cost=np.sum(cost_data)
print(total_cost)

8595005


Question 21: Store-Wise Cost
Calculate the total cost incurred by each store

In [ ]:
total_cost=np.sum(cost_data,axis=1)
for store, cost in zip(stores,total_cost):
   print(f"{store}:{cost}")

Bengaluru:1665000
Hyderabad:1685000
Chennai:1710000
Mumbai:2060005
Pune:1475000


Question 22: Category-Wise Cost
Calculate the total cost incurred for each product category across all stores.

In [ ]:
total_cost=np.sum(cost_data,axis=0)
for category, cost in zip(categories,total_cost):
   print(f"{category}:{cost}")

Electronics:3250000
Groceries:1660000
Clothing:1145000
Furniture:1045000
Beauty:660005
Sports:835000


Question 23: Most Expensive Store
Identify the store with the highest total operating cost.

In [ ]:
total_cost=np.sum(cost_data,axis=1)
max_index=np.argmax(total_cost)
print("store name: ",stores[max_index])
print("highest total operating cost: ",(total_cost[max_index]))

store name:  Mumbai
highest total operating cost:  2060005


Question 24: Lowest-Cost Store
Identify the store with the lowest total cost

In [ ]:
total_cost=np.sum(cost_data,axis=1)
min_index=np.argmin(total_cost)
print("store name: ",stores[min_index])
print("highest total operating cost: ",(total_cost[min_index]))

store name:  Pune
highest total operating cost:  1475000


Question 25: Most Expensive Product Category
Determine which product category has the highest total cost across all stores.

In [ ]:
total_cost=np.sum(cost_data,axis=0)
max_index=np.argmax(total_cost)
print("category name: ",categories[max_index])
print("highest total cost: ",total_cost[max_index])

category name:  Electronics
highest total cost:  3250000


Part 6: Profit Analysis Using Two Arrays
Question 26: Profit Matrix
Calculate the profit generated for every store and product category.

Use:

profit_data = sales_data - cost_data
Display the complete profit matrix.

In [ ]:
profit_data = sales_data - cost_data
print("Profit Matrix:")
print(profit_data)

Profit Matrix:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  89995  85000]
 [160000  95000  75000  55000  60000  60000]]


Question 27: Store-Wise Profit
Calculate the total profit generated by each store.

In [ ]:
profit_data=sales_data-cost_data
store_profit =np.sum(profit_data,axis=1)
for store,profit in zip(stores,store_profit):
    print(f"{store}:{profit}")

Bengaluru:605000
Hyderabad:610000
Chennai:600000
Mumbai:759995
Pune:505000


Question 28: Category-Wise Profit
Calculate the total profit generated by each product category.

In [ ]:
profit_data=sales_data-cost_data
category_profit =np.sum(profit_data,axis=0)
for category,profit in zip(categories,category_profit):
    print(f"{category}:{profit}")

Electronics:1040000
Groceries:525000
Clothing:455000
Furniture:370000
Beauty:349995
Sports:340000


Question 29: Most Profitable Store
Identify the store that generated the highest total profit.

Display:

Store name
Total sales
Total cost
Total profit

In [ ]:
profit_data=sales_data-cost_data
store_profit =np.sum(profit_data,axis=1)
max_index=np.argmax(store_profit)
print("store that has highest total profit: ",stores[max_index])
print("total sales: ",np.sum(sales_data[max_index]))
print("total cost: ",np.sum(cost_data[max_index]))
print("total profit: ",store_profit[max_index])

store that has highest total profit:  Mumbai
total sales:  2820000
total cost:  2060005
total profit:  759995


Question 30: Least Profitable Store
Identify the store that generated the lowest total profit.

In [ ]:
profit_data=sales_data-cost_data
store_profit =np.sum(profit_data,axis=1)
min_index=np.argmin(store_profit)
print("store that has lowest total profit: ",stores[min_index])
print("total profit: ",store_profit[min_index])


store that has lowest total profit:  Pune
total profit:  505000


Question 31: Most Profitable Category
Find the category with the highest total profit across all stores.

In [ ]:
profit_data=sales_data-cost_data
category_profit =np.sum(profit_data,axis=0)
max_index=np.argmax(category_profit)
print("category that has highest total profit: ",categories[max_index])
print("total profit: ",category_profit[max_index])

category that has highest total profit:  Electronics
total profit:  1040000


Question 32: Least Profitable Category
Find the category with the lowest total profit.

In [ ]:
profit_data=sales_data-cost_data
category_profit =np.sum(profit_data,axis=0)
min_index=np.argmin(category_profit)
print("category that has lowest total profit: ",categories[min_index])
print("total profit: ",category_profit[min_index])

category that has lowest total profit:  Sports
total profit:  340000


Question 33: Maximum Individual Profit
Find the highest profit generated by any single store-category combination.

Display:

Profit amount
Store name
Product category
Use np.unravel_index().

In [ ]:
profit_data=sales_data-cost_data
max_index=np.unravel_index(np.argmax(profit_data),profit_data.shape)
print("store name: ",stores[max_index[0]])
print("product name: ",categories[max_index[1]])


store name:  Mumbai
product name:  Electronics


Question 34: Minimum Individual Profit
Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

In [ ]:
profit_data=sales_data-cost_data
min_index=np.unravel_index(np.argmin(profit_data),profit_data.shape)
print("store name: ",stores[min_index[0]])
print("product name: ",categories[min_index[1]])

store name:  Pune
product name:  Furniture


Part 7: Profit Margin Analysis
Question 35: Profit Margin Matrix
Calculate the profit margin percentage for every store-category combination.

In [ ]:
profit_data=sales_data-cost_data
profit_margin = (profit_data / sales_data) * 100
profit_margin = np.round(profit_margin, 2)
print(profit_margin)

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 36.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


Question 36: Store-Wise Profit Margin
Calculate the overall profit margin percentage for each store using:

Store Profit Margin =
Total Store Profit / Total Store Sales × 100

In [ ]:
total_sales=np.sum(sales_data,axis=1)
profit_data=sales_data-cost_data
total_profit=np.sum(profit_data,axis=1)
store_profit_margin =np. round((total_profit / total_sales) * 100,2)
for store, margin in zip(stores, store_profit_margin):
    print(f"{store}: {margin}%")


Bengaluru: 26.65%
Hyderabad: 26.58%
Chennai: 25.97%
Mumbai: 26.95%
Pune: 25.51%


Question 37: Category-Wise Profit Margin
Calculate the overall profit margin percentage for each product category.

In [2]:
total_sales=np.sum(sales_data,axis=0)
profit_data=sales_data-cost_data
total_profit=np.sum(profit_data,axis=0)
category_profit_margin =np. round((total_profit / total_sales) * 100,2)
for category, margin in zip(categories, category_profit_margin):
    print(f"{category}: {margin}%")

Electronics: 24.24%
Groceries: 24.03%
Clothing: 28.44%
Furniture: 26.15%
Beauty: 34.65%
Sports: 28.94%


Question 38: Best Store by Profit Margin
Identify the store with the highest overall profit margin.

In [ ]:
total_sales=np.sum(sales_data,axis=1)
total_profit=np.sum(profit_data,axis=1)
store_profit_margin = np.round((total_profit / total_sales) * 100,2)
max_index = np.argmax(store_profit_margin)
print("Store Name:", stores[max_index])
print("Profit Margin:",store_profit_margin[max_index])

Store Name: Mumbai
Profit Margin: 26.95


Question 39: Best Category by Profit Margin
Identify the product category with the highest profit margin.

In [3]:
total_sales=np.sum(sales_data,axis=0)
total_profit=np.sum(profit_data,axis=0)
category_profit_margin = np.round((total_profit / total_sales) * 100,2)
max_index = np.argmax(category_profit_margin)
print("category Name:", categories[max_index])
print("Profit Margin:",category_profit_margin[max_index])

category Name: Beauty
Profit Margin: 34.65


Question 40: Low-Margin Transactions
Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

Store
Category
Sales
Cost
Profit
Profit margin
Use Boolean indexing.

In [13]:
profit_data = sales_data - cost_data
profit_margin = np.round((profit_data / sales_data) * 100, 2)
mask = profit_margin < 22
rows, cols = np.where(mask)
for r, c in zip(rows, cols):
    print(f"Store: {stores[r]}")
    print(f"Category: {categories[c]}")
    print(f"Sales: {sales_data[r, c]}")
    print(f"Cost: {cost_data[r, c]}")
    print(f"Profit: {profit_data[r, c]}")
    print(f"Profit Margin: {profit_margin[r, c]}%")

Part 8: Boolean Filtering
Question 41: High Sales Values
Find all sales values greater than ₹5,00,000.

In [13]:
print("sales values greater than 5,00,000: ",sales_data[sales_data>500000])

sales values greater than 5,00,000:  [ 850000  780000  920000 1050000  510000  690000]


Question 42: Low Sales Values
Find all sales values below ₹2,00,000.

In [14]:
print("sales values lower than 200000: ",sales_data[sales_data<200000])

sales values lower than 200000:  [190000 185000 175000]


Question 43: High Profit Values
Find all store-category combinations where profit is greater than ₹1,50,000.

In [8]:
profit_data=sales_data-cost_data
mask=profit_data>150000
rows,cols=np.where(mask)
for r ,c in zip(rows,cols):
  print("store: ",stores[r])
  print("category: ",categories[c])
  print("profit: ",profit_data[r,c])
  print()

store:  Bengaluru
category:  Electronics
profit:  210000

store:  Hyderabad
category:  Electronics
profit:  190000

store:  Chennai
category:  Electronics
profit:  220000

store:  Mumbai
category:  Electronics
profit:  260000

store:  Pune
category:  Electronics
profit:  160000



Question 44: Moderate Sales Range
Find sales values between ₹2,50,000 and ₹5,00,000.

Use np.logical_and()

In [11]:
print("sales_values: ",sales_data[np.logical_and(sales_data>=250000,sales_data<=500000)])

sales_values:  [420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


Question 45: Premium Performance
A store-category combination is considered premium when:

Sales are greater than ₹5,00,000
Profit is greater than ₹1,50,000
Find all premium-performing combinations.

In [20]:
mask=np.logical_and(sales_data>500000,profit_data>150000)
rows, cols = np.where(mask)
for r,c in zip(rows,cols):
  print("store: ",stores[r])
  print("category: ",categories[c])
  print(f"Sales: {sales_data[r, c]}")
  print(f"profits: {profit_data[r, c]}")
  print()

store:  Bengaluru
category:  Electronics
Sales: 850000
profits: 210000

store:  Hyderabad
category:  Electronics
Sales: 780000
profits: 190000

store:  Chennai
category:  Electronics
Sales: 920000
profits: 220000

store:  Mumbai
category:  Electronics
Sales: 1050000
profits: 260000

store:  Pune
category:  Electronics
Sales: 690000
profits: 160000



Question 46: Underperforming Combinations
A store-category combination is considered underperforming when:

Sales are below ₹2,50,000
Profit margin is below 25%
Find all such combinations.

In [9]:
mask=np.logical_and(sales_data<250000,profit_margin<25)
rows,cols=np.where(mask)
for r,c in zip(rows,cols):
  print("store: ",stores[r])
  print("category: ",categories[c])
  print(f"Sales: {sales_data[r, c]}")
  print(f"profits: {profit_margin[r, c]}")
  print()

store:  Pune
category:  Furniture
Sales: 225000
profits: 24.44



Question 47: Category Performance Classification
Create a new array that classifies every sales value as:

"High" when sales are at least ₹5,00,000
"Medium" when sales are between ₹2,50,000 and ₹4,99,999
"Low" when sales are below ₹2,50,000
Use np.where() or np.select().

In [10]:
classification = np.where(
    sales_data >= 500000,
    "High",
    np.where(sales_data >= 250000, "Medium", "Low")
)

print(classification)

[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


In [2]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

Question 48: Target Comparison
Compare every store’s category sales against sales_targets.

Use NumPy broadcasting.

In [13]:
print(sales_data>=sales_targets)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


Question 49: Target Achievement Matrix
Create a Boolean array where:

True means the store achieved the category target
False means the store failed to achieve the target

In [14]:
print(sales_data>=sales_targets)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


Question 50: Target Achievement Count
Calculate the number of categories in which each store achieved its target.

In [15]:
target_achievement = sales_data >= sales_targets
achievement_count = np.sum(target_achievement, axis=1)
for store, count in zip(stores, achievement_count):
    print(f"{store}: {count}")

Bengaluru: 1
Hyderabad: 4
Chennai: 2
Mumbai: 6
Pune: 0


Question 51: Best Target-Performing Store
Find the store that achieved the highest number of category targets.

In [18]:
target_achievement = sales_data >= sales_targets
achievement_count = np.sum(target_achievement, axis=1)
max_index=np.argmax(achievement_count)
print("store that achieved the highest number of category targets: ",stores[max_index])

store that achieved the highest number of category targets:  Mumbai


Question 52: Target Achievement by Category
Calculate how many stores achieved the target for each product category.

In [19]:
target_achievement = sales_data >= sales_targets
achievement_count = np.sum(target_achievement, axis=0)
for category, count in zip(categories, achievement_count):
    print(f"{category}: {count}")

Electronics: 3
Groceries: 2
Clothing: 2
Furniture: 2
Beauty: 2
Sports: 2


Question 53: Sales Target Variance
Calculate the difference between actual sales and target sales for every store.

In [22]:
print(sales_data-sales_targets)


[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


Question 54: Percentage Above or Below Target
Calculate the percentage variance from the target using:

In [6]:
variance=sales_data-sales_targets
Percentage_Variance =np.round((variance)/(sales_targets)*100,2)
print(Percentage_Variance)

[[  6.25  -6.67  -3.12  -8.33  -5.    -2.17]
 [ -2.5    2.22  -7.81   3.33   5.     4.35]
 [ 15.   -13.33   6.25 -13.33  -7.5   -6.52]
 [ 31.25  13.33  17.19  15.    25.    26.09]
 [-13.75 -10.   -12.5  -25.   -12.5  -10.87]]


Question 55: Stores Missing Electronics Target
Identify stores that failed to achieve the Electronics sales target.

In [13]:
missing=stores[sales_data[:,0]<sales_targets[0]]
print("Stores Missing Electronics Target: ",missing)


Stores Missing Electronics Target:  ['Hyderabad' 'Pune']


Question 56: Stores Achieving All Targets
Check whether any store achieved its target in all six product categories.

Use np.all().

In [16]:
achieved_target=sales_data>=sales_targets
all_targets=np.all(achieved_target,axis=1)
print(stores[all_targets])

['Mumbai']


Question 57: Stores Achieving At Least One Target
Identify stores that achieved at least one category target.

Use np.any().

In [19]:
achieved_target=sales_data>=sales_targets
any_targets=np.any(achieved_target,axis=1)
print(stores[any_targets])

['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']


In [3]:
import numpy as np

discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

Question 58: Discount Amount Matrix
Calculate the discount amount for each store-category combination.

Use broadcasting.

In [42]:
discount_amount = sales_data * discount_rates
print(discount_amount)

[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


Question 59: Sales After Discount
Calculate the net sales value after applying the category-wise discounts.

In [22]:
net_sales = sales_data - discount_amount
print(net_sales)

[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


Question 60: Profit After Discount
Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

In [24]:
print("new profit after the discounts are applied: ",net_sales-cost_data)

new profit after the discounts are applied:  [[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  69995.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


Question 61: Profit Margin After Discount
Calculate the new profit margin after applying discounts.

In [28]:
new_profit_data=net_sales-cost_data
new_profit_margin=np.round((new_profit_data/net_sales)*100,2)
print(new_profit_margin)


[[16.34 21.05 16.51 15.29 28.49 20.99]
 [15.95 19.91 16.25 17.52 27.54 21.3 ]
 [15.46 20.38 15.22 14.77 29.49 19.9 ]
 [16.4  19.5  16.86 17.65 30.43 21.46]
 [14.65 19.43 13.87 14.14 28.57 21.41]]


Question 62: Loss-Making Transactions
Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

In [34]:
loss_mask=new_profit_margin<0
rows, cols = np.where(loss_mask)
for r, c in zip(rows, cols):
    print(stores[r], "-", categories[c])



Qestion 63: Discount Impact
Calculate how much total revenue the company loses because of the proposed discounts.

In [45]:
print("Total Revenue Lost:", np.sum(discount_amount))

Total Revenue Lost: 1146350.0


Question 64: Store Most Affected by Discounts
identify the store that loses the highest amount of revenue due to discounts.

In [47]:
loss=np.sum(discount_amount,axis=1)
index=np.argmax(loss)
print("store that loses the highest amount of Revenue Lost:", stores[index])

store that loses the highest amount of Revenue Lost: Mumbai


In [4]:
import numpy as np

tax_rates = np.array([
    0.18,  # Electronics
    0.05,  # Groceries
    0.12,  # Clothing
    0.18,  # Furniture
    0.18,  # Beauty
    0.12   # Sports
])

Question 65: Tax Collection Matrix
Calculate the tax collected on sales for each store and category.

In [49]:
tax_collection = sales_data * tax_rates
print(tax_collection)

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


Question 66: Sales Including Tax
Calculate the final customer billing value after adding tax.

In [50]:
final_billing = sales_data + tax_collection
print(final_billing)

[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


Question 67: Store-Wise Tax Collection
Calculate the total tax collected by each store.

In [51]:
store_tax = np.sum(tax_collection, axis=1)
for store, tax in zip(stores, store_tax):
    print(f"{store}: {tax}")

Bengaluru: 321900.0
Hyderabad: 321200.0
Chennai: 331800.0
Mumbai: 401400.0
Pune: 274650.0


Question 68: Category-Wise Tax Collection
Calculate total tax collected for each category.

In [54]:
category_tax = np.sum(tax_collection, axis=0)
for category, tax in zip(categories, category_tax):
    print(f"{category}: {tax}")

Electronics: 772200.0
Groceries: 109250.0
Clothing: 192000.0
Furniture: 254700.0
Beauty: 181800.0
Sports: 141000.0


Question 69: Highest Tax-Contributing Store
Identify the store that contributes the highest tax amount.

In [55]:
max_index = np.argmax(store_tax)
print("Store:", stores[max_index])
print("Tax Collected:", store_tax[max_index])

Store: Mumbai
Tax Collected: 401400.0


Part 12: Array Modification
Question 70: Updated Pune Electronics Sales
The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

In [5]:
updated_sales=sales_data.copy()
updated_sales[4,0]=740000
print("Updated Pune Electronics Sales: ",updated_sales[4,0])

Updated Pune Electronics Sales:  740000


Question 71: Revised Beauty Cost
Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

In [12]:
updated_cost_data=cost_data.copy()
updated_cost_data[:,4]=updated_cost_data[:,4]*0.92
print(updated_cost_data)

[[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 147204 205000]
 [530000 310000 205000 170000 105800 145000]]


Question 72: Furniture Cost Increase
Furniture costs increase by 12% for all stores.

Update only the Furniture column.

In [14]:
updated_cost_data[:, 3] = updated_cost_data[:, 3] * 1.12
print(updated_cost_data)


[[640000 315000 220000 229600 115000 160000]
 [590000 350000 210000 252000 128800 170000]
 [700000 295000 245000 218400 110400 155000]
 [790000 390000 265000 280000 147204 205000]
 [530000 310000 205000 190400 105800 145000]]


Question 73: Store Closure Simulation
Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using np.delete().

In [17]:
updated_sales_data = np.delete(sales_data, 4, axis=0)
updated_cost_data = np.delete(cost_data, 4, axis=0)
print(updated_sales_data)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]


Question 74: Adding a New Store
A new Delhi store is opened with the following data:

delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
Add Delhi to both arrays using np.vstack().

Also add "Delhi" to the stores array.

In [20]:
delhi_sales = np.array([880000,475000,330000,290000,215000,250000])
delhi_cost = np.array([665000,360000,235000,215000,145000,180000])
updated_sales=np.vstack((sales_data,delhi_sales))
updated_cost_data=np.vstack((cost_data,delhi_cost))
updated_stores=np.append(stores,"delhi")
print("updated sales: ",updated_sales)
print("updated cost: ",updated_cost_data)
print("updated stores: ",updated_stores)

updated sales:  [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
updated cost:  [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 160005 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]
updated stores:  ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'delhi']


Question 75: Adding a New Product Category
SmartMart starts selling Home Appliances.

home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
Add the new category as a column using np.column_stack() or np.hstack().

In [22]:
home_appliance_sales = np.array([360000, 325000, 390000, 420000, 295000])
home_appliance_cost = np.array([265000, 240000, 285000, 305000, 225000])
updated_sales=np.column_stack((sales_data,home_appliance_sales))
updated_cost_data=np.column_stack((cost_data,home_appliance_cost))
print("updated sales: ",updated_sales)
print("updated cost: ",updated_cost_data)

updated sales:  [[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
updated cost:  [[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 160005 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]


Part 13: Sorting and Ranking
Question 76: Sort Stores by Sales
Sort stores in ascending order based on total sales.

Display store names and sales totals.

In [28]:
total_sales=np.sum(sales_data,axis=1)
sorted_index = np.argsort(total_sales)
for i in sorted_index:
    print(f"{stores[i]}: {total_sales[i]}")

Pune: 1980000
Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000


Question 77: Rank Stores by Profit
Rank stores from highest to lowest total profit.

Use np.argsort().

In [7]:
profit_data=sales_data-cost_data
store_profit=np.sum(profit_data,axis=1)
rank = np.argsort(store_profit)[::-1]
for i in rank:
    print(f"{stores[i]}: {store_profit[i]}")

Mumbai: 759995
Hyderabad: 610000
Bengaluru: 605000
Chennai: 600000
Pune: 505000


Question 78: Sort Categories by Revenue
Sort product categories from highest to lowest total revenue.

In [31]:
category_revenue = np.sum(sales_data, axis=0)
sorted_index = np.argsort(category_revenue)[::-1]
for i in sorted_index:
    print(f"{categories[i]}: {category_revenue[i]}")

Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Sports: 1175000
Beauty: 1010000


Question 79: Top Three Store-Category Sales
Find the three highest individual sales values in the complete sales matrix.

Display their:

Sales value
Store name
Category name

In [32]:
flat_indices = np.argsort(sales_data, axis=None)[-3:][::-1]
rows, cols = np.unravel_index(flat_indices, sales_data.shape)
for r, c in zip(rows, cols):
    print(f"Sales: {sales_data[r, c]}")
    print(f"Store: {stores[r]}")
    print(f"Category: {categories[c]}")


Sales: 1050000
Store: Mumbai
Category: Electronics
Sales: 920000
Store: Chennai
Category: Electronics
Sales: 850000
Store: Bengaluru
Category: Electronics


Question 80: Bottom Three Profits
Find the three lowest profit values in the profit matrix.

In [39]:
flat_indices = np.argsort(sales_data, axis=None)[0:3]
rows, cols = np.unravel_index(flat_indices, sales_data.shape)
for r, c in zip(rows, cols):
    print(f"Sales: {sales_data[r, c]}")
    print(f"Store: {stores[r]}")
    print(f"Category: {categories[c]}")

Sales: 175000
Store: Pune
Category: Beauty
Sales: 185000
Store: Chennai
Category: Beauty
Sales: 190000
Store: Bengaluru
Category: Beauty


Part 14: Statistical Analysis
Question 81: Sales Statistics
Calculate the following for the complete sales array:

Minimum
Maximum
Mean
Median
Standard deviation
Variance
25th percentile
50th percentile
75th percentile

In [43]:
print("Minimum:", np.min(sales_data))
print("Maximum:", np.max(sales_data))
print("Mean:", np.mean(sales_data))
print("Median:", np.median(sales_data))
print("Standard Deviation:", np.std(sales_data))
print("Variance:", np.var(sales_data))
print("25th Percentile:", np.percentile(sales_data, 25))
print("50th Percentile:", np.percentile(sales_data, 50))
print("75th Percentile:", np.percentile(sales_data, 75))

Minimum: 175000
Maximum: 1050000
Mean: 389166.6666666667
Median: 302500.0
Standard Deviation: 230322.53954448793
Variance: 53048472222.222206
25th Percentile: 228750.0
50th Percentile: 302500.0
75th Percentile: 416250.0


Question 82: Store-Wise Standard Deviation
Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

In [46]:
store_std=np.std(sales_data,axis=1)
print("Standard Deviation:", store_std)
most_variation = np.argmax(store_std)
print("\nStore with the most variation:", stores[most_variation])

Standard Deviation: [223059.53365762 194502.5706771  249265.58794453 271860.87128039
 177200.45146669]

Store with the most variation: Mumbai


Question 83: Category-Wise Standard Deviation
Determine which product category has the highest variation in sales across stores.

In [47]:
store_std=np.std(sales_data,axis=0)
print("Standard Deviation:", store_std)
most_variation = np.argmax(store_std)
print("\nStore with the most variation:", categories[most_variation])

Standard Deviation: [122539.78945632  43312.81565542  33911.64991563  41303.75285613
  26570.66051117  29832.86778035]

Store with the most variation: Electronics


Question 84: Sales Above Company Average
Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.

In [49]:
avg=np.mean(sales_data)
count = np.sum(sales_data >avg)
print("Number of sales values above average:", count)


Number of sales values above average: 10


Question 85: Outlier Detection
Treat any sales value greater than:

Mean + 1.5 × Standard Deviation
as a high-value outlier.

Identify all such sales values.

In [50]:
mean = np.mean(sales_data)
std = np.std(sales_data)
threshold = mean + 1.5 * std
outliers = sales_data[sales_data > threshold]
print("Outlier Sales Values:", outliers)

Outlier Sales Values: [ 850000  780000  920000 1050000]


Part 15: Reshaping and Transformation
Question 86: Flatten Sales Data
Convert the two-dimensional sales array into a one-dimensional array using:

flatten()
ravel()
Explain the difference between the two methods.

In [52]:
print("sales_flatten: ",sales_data.flatten()) #Returns a copy of the array.
print("sales_ravel: ",sales_data.ravel()) #Returns a view of the original array

sales_flatten:  [ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
sales_ravel:  [ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


Question 87: Reshape Sales Data
Reshape the 5 × 6 sales array into:

3 × 10
10 × 3
2 × 15
15 × 2
Verify that no data is lost.

In [53]:
print("sales_3x10: ", sales_data.reshape(3, 10))
print("sales_10x3: ", sales_data.reshape(10, 3))
print("sales_2x15: ", sales_data.reshape(2, 15))
print("sales_15x2: ",  sales_data.reshape(15, 2))

sales_3x10:  [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
sales_10x3:  [[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
sales_2x15:  [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]
sales_15x2:  [[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]

Question 88: Transpose Sales Data
Transpose the sales array so that:

Rows represent product categories
Columns represent stores
Display the new shape.

In [54]:
print("sales_transpose: ",sales_data.T)

sales_transpose:  [[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]


Question 89: Combined Sales and Cost Array
Stack sales_data and cost_data vertically.

Display the resulting shape.

In [55]:
combined_data = np.vstack((sales_data, cost_data))
print("Shape:", combined_data.shape)

Shape: (10, 6)


Question 90: Store-Level Combined Data
Create a three-dimensional array where:

First layer contains sales data
Second layer contains cost data
Use np.stack().

Display the shape of the new array.

In [58]:
combined_data = np.stack((sales_data, cost_data))
print("Shape:", combined_data.shape)

Shape: (2, 5, 6)


In [59]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

Question 91: Missing Value Detection
Find:

Total number of missing values
Location of missing values
Stores and categories containing missing values

In [60]:
missing_mask = np.isnan(sales_with_missing)
print("Total missing values:", np.sum(missing_mask))
rows, cols = np.where(missing_mask)
print("\nMissing value locations:")
for r, c in zip(rows, cols):
    print("Row:", r, "Column:", c)
print("\nStores and categories with missing values:")
for r, c in zip(rows, cols):
    print(stores[r], "-", categories[c])

Total missing values: 4

Missing value locations:
Row: 0 Column: 2
Row: 1 Column: 3
Row: 3 Column: 1
Row: 4 Column: 4

Stores and categories with missing values:
Bengaluru - Clothing
Hyderabad - Furniture
Mumbai - Groceries
Pune - Beauty


Question 92: Replace Missing Values with Zero
Replace all missing sales values with zero.

In [62]:
sales_no_missing = np.nan_to_num(sales_with_missing, nan=0)
print(sales_no_missing)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


Question 93: Replace with Company Average
Replace missing values with the overall average of available sales values.

Use np.nanmean().

In [67]:
company_avg = np.nanmean(sales_with_missing)
sales_filled = np.where(np.isnan(sales_with_missing),company_avg,sales_with_missing)
print(sales_filled)

[[ 850000.          420000.          398846.15384615  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          398846.15384615
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          398846.15384615  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   398846.15384615  205000.        ]]


Question 94: Replace with Category Average
Replace each missing value with the average sales value of its respective product category.

In [68]:
category_avg = np.nanmean(sales_with_missing,axis=0)
sales_filled = np.where(np.isnan(sales_with_missing),category_avg,sales_with_missing)
print(sales_filled)

[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


Question 95: Missing Value Impact
Compare total sales before and after replacing missing values with zero.

In [70]:
print("before replacing: ",np.nansum(sales_with_missing))
print("after replacing: ",np.sum(sales_no_missing))

before replacing:  10370000.0
after replacing:  10370000.0


Part 17: Conditional Business Decisions
Question 96: Store Performance Labels
Classify each store based on total sales:

"Excellent": Total sales above ₹28,00,000
"Good": Total sales between ₹24,00,000 and ₹28,00,000
"Needs Improvement": Total sales below ₹24,00,000
Use np.select().

In [16]:
store_total_sales = np.sum(sales_data, axis=1)
conditions = [
    store_total_sales > 2800000,
    store_total_sales >= 2400000
]
performance = np.select(
    conditions,
    ["Excellent", "Good"],
    default="Needs Improvement"
)
for i in range(len(stores)):
    print(stores[i], ":", performance[i])

Bengaluru : Needs Improvement
Hyderabad : Needs Improvement
Chennai : Needs Improvement
Mumbai : Excellent
Pune : Needs Improvement


Question 97: Profitability Classification
Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000
"Profitable": Profit between ₹1,00,000 and ₹2,00,000
"Low Profit": Profit below ₹1,00,000
"Loss": Profit below zero

In [11]:
conditions = [
    profit_data < 0,
    profit_data >= 200000,
    profit_data >= 100000,
    profit_data < 100000
]
labels = [
    "Loss",
    "Highly Profitable",
    "Profitable",
    "Low Profit"
]
profit_classification = np.select(
    conditions,
    labels,
    default="Low Profit"
)
print(profit_classification)

[['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']]


Question 98: Expansion Recommendation
A store is eligible for expansion when:

Total sales are above ₹25,00,000
Total profit is above ₹7,00,000
Overall profit margin is above 25%
Identify eligible stores.

In [21]:
store_sales = np.sum(sales_data, axis=1)
store_profit = np.sum(profit_data, axis=1)
store_profit_margin = (store_profit / store_sales) * 100

eligible = (
    (store_sales > 2500000) &
    (store_profit > 700000) &
    (store_profit_margin > 25)
)

print("Eligible stores:", stores[eligible])

Eligible stores: ['Mumbai']


Question 99: Category Promotion Recommendation
A product category should receive additional promotion when:

Average sales are below ₹3,00,000
Profit margin is above 25%
Identify the categories that satisfy these conditions.

In [22]:
category_avg_sales = np.mean(sales_data, axis=0)
category_profit = np.sum(profit_data, axis=0)
category_sales = np.sum(sales_data, axis=0)
category_profit_margin = (category_profit / category_sales) * 100
promotion = (
    (category_avg_sales < 300000) &
    (category_profit_margin > 25)
)

print(categories[promotion])

['Furniture' 'Beauty' 'Sports']


Question 100: Cost Optimization Recommendation
Find store-category combinations where:

Cost is greater than ₹2,50,000
Profit margin is below 25%
These combinations should be reviewed for cost optimization.

In [25]:
cost_optimization = (
    (cost_data > 250000) &
    (profit_margin < 25)
)
rows, cols = np.where(cost_optimization)
for r, c in zip(rows, cols):
    print(
        f"Store: {stores[r]}, "
        f"Category: {categories[c]}, "
        )

Store: Bengaluru, Category: Electronics, 
Store: Hyderabad, Category: Electronics, 
Store: Hyderabad, Category: Groceries, 
Store: Chennai, Category: Electronics, 
Store: Chennai, Category: Groceries, 
Store: Mumbai, Category: Electronics, 
Store: Mumbai, Category: Groceries, 
Store: Pune, Category: Electronics, 
Store: Pune, Category: Groceries, 


In [26]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

Question 101: Closing Stock
Calculate closing stock using:

Closing Stock = Opening Stock - Units Sold

In [31]:
closing_stock=opening_stock-units_sold
print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


Question 102: Low-Stock Identification
Identify store-category combinations where closing stock is below 30 units.

In [33]:
print(closing_stock[closing_stock<30])

[25 25 25 25 25 25 25 25 20]


Question 103: Stock Availability Percentage
Calculate the percentage of opening stock that remains unsold.

In [36]:
stock_availability = np.round((closing_stock / opening_stock) * 100,2)
print("stock availability: ",stock_availability)

stock availability:  [[20.83 15.56 20.   27.78 24.   22.22]
 [22.73 16.   17.86 25.   22.22 22.5 ]
 [19.23 16.67 15.62 29.41 25.   23.53]
 [16.67 14.55 15.71 25.   21.67 20.45]
 [25.   17.5  21.15 26.67 25.   25.  ]]


Question 104: Fast-Moving Products
A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

In [37]:
print("fast moving products: ",opening_stock[stock_availability<20])

fast moving products:  [450 500 280 130 420 320 150 550 350 400]


Question 105: Category-Wise Units Sold
Calculate the total units sold for each product category.

In [40]:
category_units_sold = np.sum(units_sold, axis=0)
print(category_units_sold)

[ 485 1950 1240  345  980  720]


Question 106: Store-Wise Units Sold
Calculate total units sold by each store.

In [44]:
store_units_sold = np.sum(units_sold, axis=1)
print(store_units_sold)

[1110 1175 1095 1390  950]


Question 107: Best Store by Unit Sales
Identify the store that sold the highest total number of units.

In [45]:
print(max(store_units_sold))

1390


Question 108: Reorder Requirement
A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.

In [46]:
print(closing_stock<25)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


Question 109: Reorder Quantity
Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

In [47]:
reorder_quantity = np.where(
    closing_stock < 25,
    100 - closing_stock,
    0)
print(reorder_quantity)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


Part 19: Advanced NumPy Questions
Question 110: Cumulative Store Sales
Calculate cumulative category sales for each store using np.cumsum().

In [48]:
cumulative_sales = np.cumsum(sales_data, axis=1)
print(cumulative_sales)

[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


Question 111: Cumulative Company Sales
Flatten the sales array and calculate cumulative company sales.

In [51]:
flatten_array=sales_data.flatten()
cumulative=np.cumsum(flatten_array)
print(cumulative)

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


Question 112: Sales Difference Between Categories
Calculate the difference between consecutive category sales for each store using np.diff()

In [52]:
sales_difference = np.diff(sales_data, axis=1)
print(sales_difference)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


Question 113: Unique Sales Values
Find all unique sales values in sales_data.

Also count the frequency of each value.

In [53]:
unique_sales, frequency = np.unique(sales_data, return_counts=True)
print("Unique Sales Values:", unique_sales)
print("Frequency:", frequency)

Unique Sales Values: [ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]
Frequency: [1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1]


Question 114: Search for Specific Sales
Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [55]:
rows, cols = np.where(sales_data == 420000)
print("Rows:", rows)
print("Columns:", cols)

Rows: [0]
Columns: [1]


Question 115: Compare Sales and Cost
Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using np.all()

In [58]:
sales_greater = sales_data > cost_data
print(sales_greater)
print("Are all combinations profitable?", np.all(sales_greater))

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
Are all combinations profitable? True


Question 116: Clip Profit Values
For reporting purposes, management wants profit values limited to:

Minimum: ₹75,000
Maximum: ₹2,50,000
Use np.clip() to create a reporting profit array.

In [59]:
reporting_profit = np.clip(profit_data, 75000, 250000)
print(reporting_profit)

[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  89995  85000]
 [160000  95000  75000  75000  75000  75000]]


Question 117: Normalize Sales Data
Normalize all sales values using min-max normalization:

Normalized Sales =
(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)

In [62]:
min_sales = np.min(sales_data)
max_sales = np.max(sales_data)
normalized_sales = np.round((sales_data - min_sales) / (max_sales - min_sales),2)
print(normalized_sales)

[[0.77 0.28 0.15 0.11 0.02 0.06]
 [0.69 0.33 0.14 0.15 0.04 0.07]
 [0.85 0.25 0.19 0.1  0.01 0.05]
 [1.   0.38 0.23 0.19 0.09 0.13]
 [0.59 0.26 0.12 0.06 0.   0.03]]


Question 118: Standardize Sales Data
Standardize sales using:

Standardized Sales =
(Sales - Mean Sales) / Standard Deviation

In [63]:
mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)
standardized_sales = (sales_data - mean_sales) / std_sales
print(standardized_sales)

[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


Question 119: Round Values
Convert profit margin values into:

Two decimal places
Nearest whole number
Floor values
Ceiling values

In [67]:
print(np.round(profit_margin,2))
print(np.round(profit_margin))
print(np.floor(profit_margin))
print(np.ceil(profit_margin))

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 36.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 36. 29.]
 [23. 23. 27. 24. 34. 29.]]
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 36. 29.]
 [23. 23. 26. 24. 34. 29.]]
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 36. 30.]
 [24. 24. 27. 25. 35. 30.]]


Question 120: Save and Load Data
Save the following arrays as NumPy binary files:

sales_data.npy
cost_data.npy
profit_data.npy
Load them back and verify that the loaded arrays are equal to the original arrays.

In [68]:
np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit_data)
loaded_sales = np.load("sales_data.npy")
loaded_cost = np.load("cost_data.npy")
loaded_profit = np.load("profit_data.npy")
print("Sales equal:", np.array_equal(sales_data, loaded_sales))
print("Cost equal:", np.array_equal(cost_data, loaded_cost))
print("Profit equal:", np.array_equal(profit_data, loaded_profit))

Sales equal: True
Cost equal: True
Profit equal: True


Part 20: Final Retail Analytics Project
Prepare a complete NumPy-based retail performance report.

Your report must contain the following information:

Company Summary
Total company sales
Total company cost
Total company profit
Overall company profit margin
Average transaction value
Highest individual sales value
Lowest individual sales value
Store Summary
For every store, display:

Total sales
Total cost
Total profit
Profit margin
Number of category targets achieved
Total units sold
Expansion eligibility
Category Summary
For every category, display:

Total sales
Total cost
Total profit
Profit margin
Average sales
Number of stores achieving the target
Total units sold
Management Recommendations
Based on the analysis, identify:

Best-performing store
Lowest-performing store
Most profitable category
Lowest-profit category
Store recommended for expansion
Category requiring additional marketing
Store-category combinations needing cost optimization
Store-category combinations requiring inventory reorder

In [73]:
import numpy as np

# =======================
# COMPANY SUMMARY
# =======================

print("========== COMPANY SUMMARY ==========")

print("Total Company Sales:", np.sum(sales_data))
print("Total Company Cost:", np.sum(cost_data))
print("Total Company Profit:", np.sum(profit_data))
print("Overall Company Profit Margin: {:.2f}%".format((np.sum(profit_data) / np.sum(sales_data)) * 100))
print("Average Transaction Value:", np.mean(sales_data))
print("Highest Individual Sales Value:", np.max(sales_data))
print("Lowest Individual Sales Value:", np.min(sales_data))


# =======================
# STORE SUMMARY
# =======================

print("\n========== STORE SUMMARY ==========")

store_sales = np.sum(sales_data, axis=1)
store_cost = np.sum(cost_data, axis=1)
store_profit = np.sum(profit_data, axis=1)
store_profit_margin = (store_profit / store_sales) * 100
store_units = np.sum(units_sold, axis=1)

expansion = (
    (store_sales > 2500000) &
    (store_profit > 700000) &
    (store_profit_margin > 25)
)

for i in range(len(stores)):
    print("\nStore:", stores[i])
    print("Total Sales:", store_sales[i])
    print("Total Cost:", store_cost[i])
    print("Total Profit:", store_profit[i])
    print("Profit Margin: {:.2f}%".format(store_profit_margin[i]))
    print("Total Units Sold:", store_units[i])
    print("Expansion Eligible:", expansion[i])


# =======================
# CATEGORY SUMMARY
# =======================

print("\n========== CATEGORY SUMMARY ==========")

category_sales = np.sum(sales_data, axis=0)
category_cost = np.sum(cost_data, axis=0)
category_profit = np.sum(profit_data, axis=0)
category_profit_margin = (category_profit / category_sales) * 100
category_avg_sales = np.mean(sales_data, axis=0)
category_units = np.sum(units_sold, axis=0)

for i in range(len(categories)):
    print("\nCategory:", categories[i])
    print("Total Sales:", category_sales[i])
    print("Total Cost:", category_cost[i])
    print("Total Profit:", category_profit[i])
    print("Profit Margin: {:.2f}%".format(category_profit_margin[i]))
    print("Average Sales:", category_avg_sales[i])
    print("Total Units Sold:", category_units[i])


# =======================
# MANAGEMENT RECOMMENDATIONS
# =======================

print("\n========== MANAGEMENT RECOMMENDATIONS ==========")

print("Best Performing Store:", stores[np.argmax(store_profit)])
print("Lowest Performing Store:", stores[np.argmin(store_profit)])

print("Most Profitable Category:", categories[np.argmax(category_profit)])
print("Lowest Profit Category:", categories[np.argmin(category_profit)])

print("Store Recommended for Expansion:")
print(stores[expansion])

promotion = (
    (category_avg_sales < 300000) &
    (category_profit_margin > 25)
)

print("Category Requiring Additional Marketing:")
print(categories[promotion])

print("\nStore-Category Combinations Needing Cost Optimization:")

cost_optimization = (
    (cost_data > 250000) &
    (profit_margin < 25)
)

rows, cols = np.where(cost_optimization)

for r, c in zip(rows, cols):
    print(stores[r], "-", categories[c])

print("\nStore-Category Combinations Requiring Inventory Reorder:")

reorder = closing_stock < 25

rows, cols = np.where(reorder)

for r, c in zip(rows, cols):
    print(stores[r], "-", categories[c])

========== COMPANY SUMMARY ==========
Total Company Sales: 11675000
Total Company Cost: 8595005
Total Company Profit: 3079995
Overall Company Profit Margin: 26.38%
Average Transaction Value: 389166.6666666667
Highest Individual Sales Value: 1050000
Lowest Individual Sales Value: 175000

========== STORE SUMMARY ==========

Store: Bengaluru
Total Sales: 2270000
Total Cost: 1665000
Total Profit: 605000
Profit Margin: 26.65%
Total Units Sold: 1110
Expansion Eligible: False

Store: Hyderabad
Total Sales: 2295000
Total Cost: 1685000
Total Profit: 610000
Profit Margin: 26.58%
Total Units Sold: 1175
Expansion Eligible: False

Store: Chennai
Total Sales: 2310000
Total Cost: 1710000
Total Profit: 600000
Profit Margin: 25.97%
Total Units Sold: 1095
Expansion Eligible: False

Store: Mumbai
Total Sales: 2820000
Total Cost: 2060005
Total Profit: 759995
Profit Margin: 26.95%
Total Units Sold: 1390
Expansion Eligible: True

Store: Pune
Total Sales: 1980000
Total Cost: 1475000
Total Profit: 505000
Pro